### ISSUE TITLE
Error running test...

### ISSUE THREAD

**Issue by Dafarkias** [Youka/LuaWAV#4]
When trying to run test.lua I get the following error-message:

wav.lua:589:  bad argument #3 to 'format' (number has no integer integration)

I've currently made no alterations to the code.  

Thanks in advance!

**Comment by Youka** [comment]
That's a problem with Lua 5.**3** bringing integers into the language. See [[5.3] Converting a floating point number to integer](http://lua-users.org/lists/lua-l/2014-11/msg00200.html).
LuaWav was written for Lua 5.**2** which has just floating point numbers - no problem. I don't plan to migrate to newer versions (but would accept pull requests) and doing it by yourself shouldn't be a big effort.

**Comment by Dafarkias** [comment]
Thanks!
